#!/bin/sh 

# An example hook script to verify what is about to be pushed.  Called by "git
# push" after it has checked the remote status, but before anything has been
# pushed.  If this script exits with a non-zero status nothing will be pushed.
#
# This hook is called with the following parameters:
#
# $1 -- Name of the remote to which the push is being done
# $2 -- URL to which the push is being done
#
# If pushing without using a named remote those arguments will be equal.
#
# Information about the commits which are being pushed is supplied as lines to
# the standard input in the form:
#
#   <local ref> <local sha1> <remote ref> <remote sha1>
#
# This sample shows how to prevent push of commits where the log message starts
# with "WIP" (work in progress).

# Get branch nameset -x	

function runStaticCheck(){

 echo "Runnig static analysis..."

 ./gradlew app:ktlintCheck app:detektCheck --daemon

# Check ktlint status
 local STATIC_CHECK_STATUS=$?

 if [ "$STATIC_CHECK_STATUS" -eq 0 ]
 then
	printf "Static analysis found no problems.\n"
	askUnitTest
 else 
	printf "Static analysis find these issues\n"	
	printf 1>&2 
	exit 1
 fi

}

function runUnitTests(){

 printf "Running unit tests\n"

 ./gradlew clean test

 #Check unit test status
 local UNIT_TEST_STATUS=$?

 if [ "$UNIT_TEST_STATUS" -eq 0 ]
 then
	printf "All unit tests passed\n"
	exit 0
 else
	printf "Unit tests failed\n"
	printf 1>&2
	exit 1
 fi
}

function askUnitTest(){

	read -p "Do you want to run unit test? Y or N" UNIT_TEST_ANSWER

	case $UNIT_TEST_ANSWER in 
	[yY])
		runUnitTests
	;;
	*)
		printf "Unit tests are not running\n"
		exit 0	
	;;

	esac
}

BRANCH=`git rev-parse --abbrev-ref HEAD`

#A non-zero exit code will abort the push

if [ "$BRANCH" -ne "wip/*" ]
then
	
	runStaticChecks	
	
fi	